version: '3'

services:
  classification-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "12000:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
