version: '3'

services:
  classification-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "10010:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
